name: Quality Checks

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Quality Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-none
          - riscv64gc-unknown-none-elf
          - aarch64-unknown-none-softfloat

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-06-01
          components: rust-src, clippy, rustfmt
          targets: ${{ matrix.target }}

      - name: Check rust version
        run: rustc --version --verbose

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Clippy (host, including integration tests)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo clippy --workspace --target ${{ matrix.target }} --all-targets --all-features -- -D warnings

      - name: Clippy (bare-metal libraries)
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        run: cargo clippy --workspace --target ${{ matrix.target }} --lib --all-features -- -D warnings

      - name: Build
        run: cargo build --workspace --target ${{ matrix.target }} --all-features
